[package]
name = "theorem-prover"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
itertools = "0.13.0"
nalgebra = "*"
regex = "1.11.1"

[[bin]]
name = "sat"

[[bin]]
name = "eqncmp"
